### ISSUE TITLE
Uncaught SyntaxError: Unexpected token v in JSON at position 0

### ISSUE THREAD

**Issue by fomenyesu** [reiinakano/fast-style-transfer-deeplearnjs#3]
Hi, I clone your project, and run it as readme. But the demo is not working. When I clicked the transfer button, I got the follow error: 
Uncaught SyntaxError: Unexpected token v in JSON at position 0.

Here is the return of network.:
version https://git-lfs.github.com/spec/v1
oid sha256:e03432142aa5e7f85776094d69bf5b90b11ba4498026d5ba2c73fefefbe35bf9
size 4689

**Comment by reiinakano** [comment]
Hmm, I think you may need to do `git lfs pull`? Can you confirm that `src/ckpts` folder actually contains the big 6MB folders?

I'm not very well-versed in the details of lfs, but you probably need to install Git LFS

Either way, the issue is that you need to pull down the files stored in Git LFS as well, because right now you don't have them (only the pointer files).

**Comment by reiinakano** [comment]
After doing a bit of digging, this is likely the problem you're having. To fix, please install Git LFS

https://help.github.com/articles/collaboration-with-git-large-file-storage/

**Comment by reiinakano** [comment]
As LFS is no longer used, this issue is no longer relevant.

**Comment by fomenyesu** [comment]
Thanks!
